name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            git \
            python3-pip \
            python3-setuptools \
            python3-dev \
            python3-venv \
            libssl-dev \
            zlib1g-dev \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev \
            wget \
            curl \
            llvm \
            libncurses5-dev \
            libncursesw5-dev \
            xz-utils \
            tk-dev \
            libffi-dev \
            liblzma-dev \
            python-openssl \
            unzip \
            openjdk-8-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            ccache \
            cmake \
            ninja-build \
            libffi-dev \
            libxml2-dev \
            libxslt1-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev \
            libblas-dev \
            liblapack-dev \
            gfortran \
            libatlas-base-dev \
            libhdf5-dev \
            libopenblas-dev \
            libxrender1 \
            libxext6 \
            xvfb

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: 21.3.6528147
        cmake-version: 3.18.1
        build-tools-version: 30.0.3
        platform: android-30

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --upgrade Cython==0.29.33
        pip install buildozer==1.5.0
        pip install -r requirements.txt

    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build APK
      run: |
        # Create bin directory if it doesn't exist
        mkdir -p bin
        
        # Initialize buildozer if needed
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
        # Set environment variables
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        export PATH=$PATH:$ANDROID_HOME/platform-tools
        export PATH=$PATH:$ANDROID_HOME/tools/bin
        
        # Build with verbose output
        echo "Starting build..."
        buildozer -v android debug 2>&1 | tee build.log
        
        # Check build result
        BUILD_RESULT=${PIPESTATUS[0]}
        
        # Create a summary of the build
        echo "=== Build Summary ===" > build-summary.txt
        echo "Build exit code: $BUILD_RESULT" >> build-summary.txt
        echo "\n=== Environment Variables ===" >> build-summary.txt
        env | sort >> build-summary.txt
        echo "\n=== Directory Structure ===" >> build-summary.txt
        find . -type d | sort >> build-summary.txt
        echo "\n=== Bin Directory Contents ===" >> build-summary.txt
        ls -la bin/ 2>/dev/null || echo "bin/ directory not found" >> build-summary.txt
        
        # Exit with build status
        if [ $BUILD_RESULT -ne 0 ]; then
          echo "Build failed with exit code $BUILD_RESULT"
          echo "\n=== Last 50 lines of build log ===" >> build-summary.txt
          tail -n 50 build.log >> build-summary.txt
          echo "\n=== Buildozer Version ===" >> build-summary.txt
          buildozer version >> build-summary.txt
          exit $BUILD_RESULT
        fi

    - name: Upload APK
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: voltmatic-apk
        path: |
          bin/*.apk
          build.log
          build-summary.txt
        if-no-files-found: warn
        retention-days: 7
