name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev
        sudo apt-get install -y libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3
        ndk-version: 23b

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0
        pip install -r requirements.txt

    - name: Accept Android licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Build APK
      run: |
        # Create bin directory if it doesn't exist
        mkdir -p bin
        
        # Build with verbose output
        echo "Starting build..."
        buildozer -v android debug 2>&1 | tee build.log
        
        # Check build result
        BUILD_RESULT=${PIPESTATUS[0]}
        
        # Create a summary of the build
        echo "=== Build Summary ===" > build-summary.txt
        echo "Build exit code: $BUILD_RESULT" >> build-summary.txt
        echo "\n=== Directory Structure ===" >> build-summary.txt
        find . -type d | sort >> build-summary.txt
        echo "\n=== Bin Directory Contents ===" >> build-summary.txt
        ls -la bin/ 2>/dev/null || echo "bin/ directory not found" >> build-summary.txt
        
        # Exit with build status
        if [ $BUILD_RESULT -ne 0 ]; then
          echo "Build failed with exit code $BUILD_RESULT"
          echo "\n=== Last 50 lines of build log ===" >> build-summary.txt
          tail -n 50 build.log >> build-summary.txt
          exit $BUILD_RESULT
        fi

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: voltmatic-apk
        path: |
          bin/*.apk
          build.log
          build-summary.txt
        if-no-files-found: error
