name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Cancel in-progress runs when new commits are pushed
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    env:
      ANDROID_HOME: /opt/android-sdk
      ANDROID_SDK_ROOT: /opt/android-sdk
      ANDROID_NDK_HOME: /opt/android-sdk/ndk/21.3.6528147

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            git \
            python3-pip \
            python3-dev \
            python3-venv \
            libssl-dev \
            zlib1g-dev \
            libffi-dev \
            libxml2-dev \
            libxslt1-dev \
            libjpeg-dev \
            libpng-dev \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            cmake \
            openjdk-11-jdk \
            unzip \
            wget \
            curl \
            ninja-build

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user --upgrade Cython==0.29.33
        pip install --user buildozer
        export PATH=$PATH:$HOME/.local/bin/
        buildozer --version

    - name: Set up Android SDK and NDK
      run: |
        sudo mkdir -p $ANDROID_HOME
        sudo chown $USER:$USER $ANDROID_HOME
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Install Android Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        mkdir -p $ANDROID_HOME/cmdline-tools/latest
        unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools/
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
        rm -r $ANDROID_HOME/cmdline-tools/cmdline-tools
        
        # Accept licenses
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Install required Android packages
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-30" \
            "build-tools;30.0.3" \
            "ndk;21.3.6528147"
        
        # Set environment variables for buildozer
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.3.6528147" >> $GITHUB_ENV
        
        # Add Android tools to PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Configure buildozer to use pre-installed SDK/NDK
      run: |
        # Verify buildozer.spec exists and has correct configuration
        if [ ! -f buildozer.spec ]; then
          echo "buildozer.spec not found!"
          exit 1
        fi
        
        # Update buildozer.spec to use our pre-installed SDK/NDK
        sed -i "s|android.ndk_path = .*|android.ndk_path = $ANDROID_HOME/ndk/21.3.6528147|" buildozer.spec
        sed -i "s|android.sdk_path = .*|android.sdk_path = $ANDROID_HOME|" buildozer.spec
        
        # Display current configuration for debugging
        echo "=== Updated buildozer.spec configuration ==="
        grep -E "(requirements|android\.(api|minapi|ndk|sdk|archs|accept_sdk_license|ndk_path|sdk_path))" buildozer.spec || true
        
        # Verify environment variables
        echo "=== Environment Variables ==="
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
        
        # Check if Android SDK/NDK are properly installed
        echo "=== Verifying SDK/NDK installation ==="
        ls -la $ANDROID_HOME/ || echo "Android SDK directory not found"
        ls -la $ANDROID_HOME/ndk/ || echo "NDK directory not found"
        ls -la $ANDROID_HOME/ndk/21.3.6528147/ || echo "Specific NDK version not found"

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Pre-build checks
      run: |
        echo "=== Pre-build Validation ==="
        
        # Check if main.py exists
        if [ ! -f main.py ]; then
          echo "ERROR: main.py not found!"
          exit 1
        fi
        
        # Check if all required screen files exist
        echo "Checking screen files..."
        for screen in home_screen clients_screen survey_screen client_form_screen surveys_list_screen call_history_screen; do
          if [ ! -f "app/screens/${screen}.py" ]; then
            echo "WARNING: app/screens/${screen}.py not found"
          fi
          if [ ! -f "app/screens/${screen}.kv" ]; then
            echo "WARNING: app/screens/${screen}.kv not found"
          fi
        done
        
        # Check if database.py exists
        if [ ! -f app/database.py ]; then
          echo "ERROR: app/database.py not found!"
          exit 1
        fi
        
        # Check if assets directory exists
        if [ ! -d assets ]; then
          echo "WARNING: assets directory not found, creating..."
          mkdir -p assets/images assets/icons
        fi
        
        # Validate buildozer.spec syntax
        echo "Validating buildozer.spec..."
        python -c "import configparser; config = configparser.ConfigParser(); config.read('buildozer.spec'); print('buildozer.spec syntax is valid')"

    - name: Build APK
      run: |
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$HOME/.local/bin
        export ANDROID_HOME=$ANDROID_HOME
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.3.6528147
        
        # Debug environment
        echo "=== Environment Debug ==="
        echo "PATH: $PATH"
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
        echo "Python version: $(python --version)"
        echo "Buildozer version: $(buildozer --version)"
        
        # Check buildozer.spec
        echo "=== Buildozer Config Check ==="
        if [ -f buildozer.spec ]; then
          echo "buildozer.spec found"
          grep -E "requirements|android\.(api|minapi|ndk|sdk)" buildozer.spec
        else
          echo "ERROR: buildozer.spec not found!"
          exit 1
        fi
        
        # Create necessary directories
        mkdir -p bin
        
        # Build with buildozer (capture exit code)
        echo "Starting buildozer build..."
        echo "=== Buildozer command about to run ==="
        which buildozer
        buildozer --version
        
        set +e  # Don't exit on error
        
        # Try buildozer clean first to ensure fresh build
        echo "=== Cleaning buildozer cache ==="
        buildozer android clean || true
        
        # Run buildozer with explicit debug flag
        echo "=== Running buildozer android debug ==="
        buildozer android debug 2>&1 | tee build.log
        BUILD_EXIT_CODE=$?
        
        # If that fails, try release build
        if [ $BUILD_EXIT_CODE -ne 0 ]; then
          echo "=== Debug build failed, trying release build ==="
          buildozer android release 2>&1 | tee -a build.log
          BUILD_EXIT_CODE=$?
        fi
        
        set -e  # Re-enable exit on error
        
        echo "=== Buildozer completed with exit code: $BUILD_EXIT_CODE ==="
        
        echo "Build completed with exit code: $BUILD_EXIT_CODE"
        
        # Always show build log tail for debugging
        echo "=== Build Log Tail (last 100 lines) ==="
        tail -100 build.log
        
        # Comprehensive APK search and debugging
        echo "=== Comprehensive APK Search ==="
        echo "Searching entire filesystem for APK files..."
        find . -name "*.apk" -type f 2>/dev/null | while read apk; do
          echo "Found APK: $apk"
          ls -la "$apk"
          file "$apk"
        done
        
        echo "=== Buildozer Directory Structure ==="
        if [ -d .buildozer ]; then
          find .buildozer -type f -name "*.apk" 2>/dev/null || echo "No APK files in .buildozer"
          echo "=== Buildozer android platform contents ==="
          ls -la .buildozer/android/platform/ 2>/dev/null || echo "No platform directory"
          if [ -d .buildozer/android/platform ]; then
            find .buildozer/android/platform -name "*apk*" -o -name "*dist*" -o -name "*build*" 2>/dev/null | head -10
          fi
        else
          echo ".buildozer directory does not exist"
        fi
        
        echo "=== Checking build log for APK generation ==="
        grep -i "apk\|package\|signing\|zipalign" build.log | tail -10 || echo "No APK-related messages in build log"
        
        # Try to find and copy any APK files
        APK_FOUND=false
        APK_FILES=$(find . -name "*.apk" -type f 2>/dev/null)
        
        if [ -n "$APK_FILES" ]; then
          echo "=== Copying found APK files to bin directory ==="
          mkdir -p bin
          for apk in $APK_FILES; do
            echo "Copying $apk to bin/"
            cp "$apk" "bin/$(basename "$apk")"
            APK_FOUND=true
          done
        fi
        
        # Final check and force APK creation if needed
        if [ "$APK_FOUND" = true ]; then
          echo "=== APK files successfully located ==="
          ls -la bin/
        else
          echo "=== NO APK FILES FOUND - Trying manual APK creation ==="
          
          # Check if we have gradle build outputs
          if [ -d .buildozer/android/platform ]; then
            echo "=== Searching for gradle build outputs ==="
            find .buildozer/android/platform -name "*.apk" -o -name "app-debug.apk" -o -name "app-release.apk" 2>/dev/null || echo "No gradle APKs found"
            
            # Try to find any built APK in gradle outputs
            GRADLE_APK=$(find .buildozer/android/platform -name "*.apk" 2>/dev/null | head -1)
            if [ -n "$GRADLE_APK" ]; then
              echo "Found gradle APK: $GRADLE_APK"
              cp "$GRADLE_APK" bin/voltmatic-app.apk
              APK_FOUND=true
            fi
          fi
          
          # If still no APK, create a dummy file to indicate the issue
          if [ "$APK_FOUND" = false ]; then
            echo "Creating error report file..."
            echo "APK generation failed. Build exit code: $BUILD_EXIT_CODE" > bin/BUILD_FAILED.txt
            echo "Check build.log for details" >> bin/BUILD_FAILED.txt
            echo "Last 100 lines of build log:" >> bin/BUILD_FAILED.txt
            tail -100 build.log >> bin/BUILD_FAILED.txt
          fi
        fi

    - name: Upload APK artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: apk-artifact
        path: |
          bin/*
          .buildozer/**/*.apk
          build.log
          buildozer.spec
        if-no-files-found: warn

    - name: Create build summary
      if: always()
      run: |
        echo "=== Build Summary ===" > build-summary.txt
        echo "Build exit code: $?" >> build-summary.txt
        echo "\n=== Environment Variables ===" >> build-summary.txt
        env | sort >> build-summary.txt
        echo "\n=== Directory Structure ===" >> build-summary.txt
        find . -type d | sort >> build-summary.txt
        echo "\n=== Bin Directory Contents ===" >> build-summary.txt
        ls -la bin/ 2>/dev/null || echo "bin/ directory not found" >> build-summary.txt

    - name: Upload build summary
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-summary
        path: build-summary.txt
        if-no-files-found: warn
        retention-days: 7
