name: Build Android APK - Ultimate Solution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install buildozer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-pip python3-dev libssl-dev zlib1g-dev libffi-dev autoconf libtool pkg-config cmake openjdk-11-jdk unzip wget curl
        pip install --user buildozer cython
        pip install -r requirements.txt

    - name: Set up Android SDK
      run: |
        export ANDROID_HOME=/opt/android-sdk
        export ANDROID_SDK_ROOT=/opt/android-sdk
        export ANDROID_NDK_HOME=/opt/android-sdk/ndk/25.2.9519653
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg

    - name: Build APK with buildozer
      run: |
        export PATH=$PATH:$HOME/.local/bin
        mkdir -p bin
        timeout 30m buildozer android debug --verbose || echo "Build completed or timed out"

    - name: Find and collect APK files
      run: |
        echo "Searching for APK files..."
        find . -name "*.apk" -type f 2>/dev/null | while read apk; do
          echo "Found APK: $apk"
          cp "$apk" "bin/$(basename "$apk")"
          cp "$apk" "bin/voltmatic-app.apk"
        done
        
        echo "Final results:"
        ls -la bin/ || echo "No bin directory"
        
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "SUCCESS: APK files found!"
        else
          echo "No APK files found"
          echo "NO_APK_FOUND" > bin/status.txt
        fi

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: apk-files
        path: bin/
        if-no-files-found: warn
